import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import fs from 'fs';
import matter from 'gray-matter';
import Link from 'next/link';
import Tag from "../components/Tag";

export async function getStaticProps() {
  const files = fs.readdirSync('posts');
  const posts = files.map((fileName) => {
    const slug = fileName.replace('.md', '');
    const readFile = fs.readFileSync(`posts/${fileName}`, 'utf8');
    const { data: frontmatter } = matter(readFile);

    return {
      slug,
      frontmatter,
    };
  });
  return {
    props: {
      posts,
    },
  };
}



export default function Home({ posts }) {
  return (
    <div>
      <Head>
        <title>Lorem Ipsum</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
      </Head>
      <main className={styles.main}>
        <h1 className={`text-2xl sm:text-4xl md:text-5xl lg:text-6xl m-0 leading-[3rem]`}>
          <span className={'font-bold'}>Welcome to </span><a className={'font-bold text-highlight hover:underline'}>Lorem Ipsum!</a>
        </h1>

        <p className={`text-lg m-6 sm:text-2xl sm:m-12 ${styles.description}`}>
          Vivamus eu volutpat sapien, in commodo leo.
        </p>

        <div className={styles.grid}>
          {posts.map(({ slug, frontmatter }) => (
            <Link href={`/posts/${slug}`} key={slug} >
              <a className={`hover:shadow-md shadow-laurel shadow-sm max-w-[15rem] sm:max-w-xs ${styles.card}`}>
                <Image
                  className={'rounded-2xl'}
                  width={650}
                  height={340}
                  alt={frontmatter.title}
                  src={`/${frontmatter.socialImage}`}
                />
                {frontmatter.title.length >  37 ? <h2>{frontmatter.title.slice(0, 37) + '...'}</h2> : <h2>{frontmatter.title}</h2>}
                <p>{frontmatter.metaDesc}</p>
                {(frontmatter.tags).map((tag) =>
                  <Tag key={tag}>{tag}</Tag>
                )}
              </a>
            </Link>
            ))}
        </div>
      </main>
    </div>
  )
}
